// LocalLink Phase 1 sample PM2 and host-service topology.
module.exports = {
  apps: [
    {
      name: 'locallink-mcp-core',
      cwd: '.',
      script: './bin/locallink.js',
      args: 'mcp',
      locallink: {
        name: 'LocalLink MCP Core',
        group: 'pm2',
        runtime: 'pm2',
        dockerfile: './blueprints/locallink-mcp-core.Dockerfile',
        envVars: [],
        docsUrl: 'https://modelcontextprotocol.io',
        notes: 'Stdio bridge for AI agents.',
        detail: 'Exposes read/write lifecycle control and structural config tools to local assistants.',
        tags: ['stdio', 'ai', 'config'],
      },
    },
    {
      name: 'queue-worker',
      cwd: '.',
      script: './scripts/mock-worker.js',
      env: {
        PORT: process.env.QUEUE_WORKER_PORT || '6012',
      },
      locallink: {
        name: 'Queue Worker',
        group: 'pm2',
        runtime: 'pm2',
        dockerfile: './blueprints/queue-worker.Dockerfile',
        portEnv: 'QUEUE_WORKER_PORT',
        dependsOn: ['Postgres Compose'],
        downstream: ['LocalLink Dashboard UI'],
        envVars: ['QUEUE_WORKER_PORT', 'POSTGRES_PORT'],
        docsUrl: 'https://pm2.keymetrics.io/docs/usage/application-declaration/',
        notes: 'Background task runner.',
        detail: 'Consumes local jobs and emits terminal logs for the dashboard tailer.',
        tags: ['pm2', 'worker', 'jobs'],
      },
    },
    {
      name: 'locallink-dashboard-ui',
      cwd: '.',
      script: './bin/locallink.js',
      args: 'web',
      env: {
        LOCALLINK_WEB_PORT: process.env.LOCALLINK_WEB_PORT || '4010',
      },
      locallink: {
        name: 'LocalLink Dashboard UI',
        group: 'pwa',
        runtime: 'pm2',
        dockerfile: './blueprints/locallink-dashboard-ui.Dockerfile',
        portEnv: 'LOCALLINK_WEB_PORT',
        dependsOn: ['Queue Worker'],
        envVars: ['LOCALLINK_WEB_PORT'],
        docsUrl: 'https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps',
        notes: 'Local dashboard shell.',
        detail: 'Installable dashboard served from the local-only control plane.',
        tags: ['pwa', 'ui', 'installable'],
      },
    },
    {
      name: 'Windows File Indexer',
      cwd: '.',
      script: 'task',
      args: 'windows-file-indexer:start',
      locallink: {
        group: 'windows',
        runtime: 'taskfile',
        taskName: 'windows-file-indexer',
        windowsProcessName: 'SearchIndexer.exe',
        docsUrl: 'https://learn.microsoft.com/windows/win32/search/-search-3x-wds-overview',
        notes: 'Local file watcher bridge.',
        detail: 'Detects desktop-side changes and keeps the orchestrator aware of host activity.',
        tags: ['windows', 'watcher', 'fs'],
      },
    },
    {
      name: 'AgentGateway Proxy',
      cwd: '.',
      script: 'task',
      args: 'agentgateway-proxy:start',
      locallink: {
        group: 'windows',
        runtime: 'taskfile',
        taskName: 'agentgateway-proxy',
        windowsProcessName: 'AgentGateway.exe',
        dependsOn: ['Pocket ID'],
        docsUrl: 'https://tailscale.com/docs/features/tailscale-serve',
        notes: 'Phase 2 bridge placeholder.',
        detail: 'Tailscale edge placeholder that privately publishes Pocket ID and internal application origins.',
        tags: ['future', 'gateway', 'off'],
      },
    },
  ],
};
